# Generated by Django 5.1.15 on 2026-04-01 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BOOKED', 'Reservado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], db_index=True, default='AVAILABLE', max_length=12, verbose_name='Estado')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID evento Google Calendar')),
                ('google_meet_link', models.URLField(blank=True, verbose_name='Enlace Google Meet')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de la cita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time'), name='unique_slot_per_datetime')],
            },
        ),
    ]
