# Generated by Django 5.2.15 on 2026-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (invitado)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (invitado)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre y apellido (invitado)'),
        ),
    ]
