# Generated by Django 5.1.15 on 2026-04-01 18:15

import django.db.models.deletion
import files_manager.models
import private_storage.fields
import private_storage.storage.files
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=files_manager.models.shared_file_upload_path, verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('PDF', 'Documento PDF'), ('VIDEO', 'Video'), ('IMAGE', 'Imagen'), ('OTHER', 'Otro')], default='PDF', max_length=10, verbose_name='Tipo de archivo')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Público'), ('REGISTERED', 'Pacientes registrados'), ('PRIVATE', 'Paciente específico')], db_index=True, default='REGISTERED', max_length=12, verbose_name='Visibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo compartido',
                'verbose_name_plural': 'Archivos compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files_manager.sharedfile', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Permiso de archivo',
                'verbose_name_plural': 'Permisos de archivo',
                'constraints': [models.UniqueConstraint(fields=('shared_file', 'patient'), name='unique_file_patient_permission')],
            },
        ),
    ]
