# Generated by Django 5.1.15 on 2026-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='locality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localidad'),
        ),
    ]
