# Generated by Django 5.1.15 on 2026-06-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con descuento'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='En oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_label',
            field=models.CharField(blank=True, help_text='Ej: 2x1, 30% OFF, Envío gratis', max_length=100, verbose_name='Etiqueta promoción'),
        ),
    ]
