# Generated by Django 5.2.15 on 2026-06-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_product_is_featured_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, help_text='Descripción más detallada del producto', verbose_name='Detalles'),
        ),
    ]
