# Generated by Django 5.2.15 on 2026-07-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pregunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sección del cuestionario',
                'verbose_name_plural': 'Secciones del cuestionario',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Bajo, Moderado, Alto', max_length=100, verbose_name='Nombre')),
                ('min_score', models.IntegerField(default=0, verbose_name='Puntaje mínimo')),
                ('max_score', models.IntegerField(default=0, verbose_name='Puntaje máximo')),
                ('color', models.CharField(choices=[('green', 'Verde'), ('yellow', 'Amarillo'), ('red', 'Rojo')], max_length=20, verbose_name='Color')),
                ('message_female', models.TextField(help_text='Mensaje que se muestra para pacientes femeninas', verbose_name='Mensaje (Femenino)')),
                ('message_male', models.TextField(help_text='Mensaje que se muestra para pacientes masculinos', verbose_name='Mensaje (Masculino)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Rango de puntuación',
                'verbose_name_plural': 'Rangos de puntuación',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='patients.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='patients.quizsection', verbose_name='Sección'),
        ),
    ]
