# Generated by Django 5.2.15 on 2026-08-02 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_seed_microbiota_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=512, verbose_name='Access token')),
                ('refresh_token', models.CharField(blank=True, max_length=512, verbose_name='Refresh token')),
                ('public_key', models.CharField(blank=True, max_length=256, verbose_name='Public key')),
                ('mp_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de usuario (MP)')),
                ('token_type', models.CharField(blank=True, max_length=64, verbose_name='Tipo de token')),
                ('expires_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración del token (segundos)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='El token expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Credencial de Mercado Pago',
                'verbose_name_plural': 'Credenciales de Mercado Pago',
            },
        ),
    ]
