# Generated by Django 5.2.15 on 2026-07-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_question_quizsection_scorerange_answeroption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerange',
            name='max_score_male',
            field=models.IntegerField(default=0, verbose_name='Puntaje máximo (Masculino)'),
        ),
        migrations.AddField(
            model_name='scorerange',
            name='min_score_male',
            field=models.IntegerField(default=0, verbose_name='Puntaje mínimo (Masculino)'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Puntaje máximo (Femenino)'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='min_score',
            field=models.IntegerField(default=0, verbose_name='Puntaje mínimo (Femenino)'),
        ),
    ]
