# Generated by Django 5.2.15 on 2026-08-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_mercadopagocredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access token')),
                ('refresh_token', models.TextField(verbose_name='Refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=64, verbose_name='Tipo de token')),
                ('expires_at', models.DateTimeField(verbose_name='El token expira en')),
                ('google_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Google')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Dra.')),
            ],
            options={
                'verbose_name': 'Credencial de Google Calendar',
                'verbose_name_plural': 'Credenciales de Google Calendar',
            },
        ),
    ]
