# Generated by Django 5.2.15 on 2026-08-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_googlecalendarcredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Leído'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de respuestas'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('READ', 'Leído'), ('REPLIED', 'Respondido'), ('ARCHIVED', 'Archivado')], db_index=True, default='NEW', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LeadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Respuesta')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='patients.lead', verbose_name='Consulta')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Respuesta a consulta',
                'verbose_name_plural': 'Respuestas a consultas',
                'ordering': ['sent_at'],
            },
        ),
    ]
