# Generated by Django 5.2.15 on 2026-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_lead_is_read_lead_reply_count_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message_html',
            field=models.TextField(blank=True, verbose_name='Mensaje HTML'),
        ),
    ]
