# Generated by Django 5.2.15 on 2026-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_lead_message_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltimelineentry',
            name='details_html',
            field=models.TextField(blank=True, verbose_name='Detalle clínico HTML'),
        ),
    ]
